### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by TomashKhamlai** [TomashKhamlai/homepage#12]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by KaterynaToporkova** [comment]
### Ryu Hoshi (リュウ Ryū)
* https://www.facebook.com/profile.php?id=100004808958030
* ryuwins@gmail.com
* https://twitter.com/denjinryu
* https://www.instagram.com/sworn_ryu/

**Comment by KaterynaToporkova** [comment]
### ― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by TomashKhamlai** [comment]
<h2>Resume</h2>
<p> &mdash;I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.</p>
